import { ClerkProvider } from "@clerk/nextjs";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<head>
					<ColorSchemeScript />
				</head>
				<MantineProvider>{children}</MantineProvider>
			</html>
		</ClerkProvider>
	);
}
